# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manageDB.ui'
#
# Created: Sat Nov 19 19:08:03 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ManageDB(object):
    def setupUi(self, ManageDB):
        ManageDB.setObjectName(_fromUtf8("ManageDB"))
        ManageDB.setEnabled(True)
        ManageDB.resize(571, 455)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 241, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        ManageDB.setPalette(palette)
        ManageDB.setWindowOpacity(1.0)
        ManageDB.setAutoFillBackground(True)
        ManageDB.setStyleSheet(_fromUtf8(""))
        ManageDB.setSizeGripEnabled(False)
        self.addNewPersonButton = QtGui.QPushButton(ManageDB)
        self.addNewPersonButton.setGeometry(QtCore.QRect(290, 340, 151, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addNewPersonButton.setIcon(icon)
        self.addNewPersonButton.setIconSize(QtCore.QSize(20, 20))
        self.addNewPersonButton.setObjectName(_fromUtf8("addNewPersonButton"))
        self.deletePersonButton = QtGui.QPushButton(ManageDB)
        self.deletePersonButton.setEnabled(True)
        self.deletePersonButton.setGeometry(QtCore.QRect(290, 380, 151, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Delete_Icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deletePersonButton.setIcon(icon1)
        self.deletePersonButton.setIconSize(QtCore.QSize(24, 24))
        self.deletePersonButton.setObjectName(_fromUtf8("deletePersonButton"))
        self.editButton = QtGui.QPushButton(ManageDB)
        self.editButton.setEnabled(True)
        self.editButton.setGeometry(QtCore.QRect(120, 340, 161, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editButton.setIcon(icon2)
        self.editButton.setIconSize(QtCore.QSize(20, 20))
        self.editButton.setObjectName(_fromUtf8("editButton"))
        self.helpButton = QtGui.QPushButton(ManageDB)
        self.helpButton.setGeometry(QtCore.QRect(470, 0, 98, 27))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/help.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpButton.setIcon(icon3)
        self.helpButton.setIconSize(QtCore.QSize(25, 25))
        self.helpButton.setCheckable(False)
        self.helpButton.setChecked(False)
        self.helpButton.setObjectName(_fromUtf8("helpButton"))
        self.personList = QtGui.QListWidget(ManageDB)
        self.personList.setGeometry(QtCore.QRect(120, 120, 321, 191))
        self.personList.setObjectName(_fromUtf8("personList"))
        item = QtGui.QListWidgetItem()
        self.personList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.personList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.personList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.personList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.personList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.personList.addItem(item)
        item = QtGui.QListWidgetItem()
        self.personList.addItem(item)
        self.logo = QtGui.QLabel(ManageDB)
        self.logo.setGeometry(QtCore.QRect(0, 0, 411, 81))
        self.logo.setText(_fromUtf8(""))
        self.logo.setPixmap(QtGui.QPixmap(_fromUtf8("icons/logo.png")))
        self.logo.setObjectName(_fromUtf8("logo"))
        self.title = QtGui.QLabel(ManageDB)
        self.title.setGeometry(QtCore.QRect(120, 100, 111, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.title.setFont(font)
        self.title.setObjectName(_fromUtf8("title"))
        self.titleLogo = QtGui.QLabel(ManageDB)
        self.titleLogo.setGeometry(QtCore.QRect(60, 100, 51, 61))
        self.titleLogo.setText(_fromUtf8(""))
        self.titleLogo.setPixmap(QtGui.QPixmap(_fromUtf8("icons/choosen.png")))
        self.titleLogo.setObjectName(_fromUtf8("titleLogo"))
        self.backButton = QtGui.QPushButton(ManageDB)
        self.backButton.setGeometry(QtCore.QRect(470, 420, 98, 27))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("icons/back.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backButton.setIcon(icon4)
        self.backButton.setIconSize(QtCore.QSize(23, 22))
        self.backButton.setCheckable(False)
        self.backButton.setChecked(False)
        self.backButton.setObjectName(_fromUtf8("backButton"))
        self.editRecordButton = QtGui.QPushButton(ManageDB)
        self.editRecordButton.setEnabled(True)
        self.editRecordButton.setGeometry(QtCore.QRect(120, 380, 161, 31))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("icons/personrecords.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editRecordButton.setIcon(icon5)
        self.editRecordButton.setIconSize(QtCore.QSize(20, 20))
        self.editRecordButton.setObjectName(_fromUtf8("editRecordButton"))

        self.retranslateUi(ManageDB)
        QtCore.QMetaObject.connectSlotsByName(ManageDB)

    def retranslateUi(self, ManageDB):
        ManageDB.setWindowTitle(_translate("ManageDB", "ManageDB", None))
        self.addNewPersonButton.setText(_translate("ManageDB", "Add new person", None))
        self.deletePersonButton.setText(_translate("ManageDB", "Delete person", None))
        self.editButton.setText(_translate("ManageDB", "Edit person info", None))
        self.helpButton.setText(_translate("ManageDB", "Help", None))
        __sortingEnabled = self.personList.isSortingEnabled()
        self.personList.setSortingEnabled(False)
        item = self.personList.item(0)
        item.setText(_translate("ManageDB", "shai charsky", None))
        item = self.personList.item(1)
        item.setText(_translate("ManageDB", "Youlanda Tull", None))
        item = self.personList.item(2)
        item.setText(_translate("ManageDB", "idan ash", None))
        item = self.personList.item(3)
        item.setText(_translate("ManageDB", "Aliza Pilger", None))
        item = self.personList.item(4)
        item.setText(_translate("ManageDB", "Alberto Oelke", None))
        item = self.personList.item(5)
        item.setText(_translate("ManageDB", "Suzanna Pennebaker", None))
        item = self.personList.item(6)
        item.setText(_translate("ManageDB", "Rosalva Umland", None))
        self.personList.setSortingEnabled(__sortingEnabled)
        self.title.setText(_translate("ManageDB", "choose person:", None))
        self.backButton.setText(_translate("ManageDB", "Back", None))
        self.editRecordButton.setText(_translate("ManageDB", "Edit person records", None))

import 1_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ManageDB = QtGui.QDialog()
    ui = Ui_ManageDB()
    ui.setupUi(ManageDB)
    ManageDB.show()
    sys.exit(app.exec_())

